image: node:18


stages:
  - pre-setup
  - setup
  - type-check
  - lint-check

pre-install:
  stage:
    - pre-setup
  script:
    - npm install pnpm
  only:
    - master
    - dev


install:
  stage:
    -setup
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
      - pnpm i --no-frozen-lockfile
  cache:
      key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm-store
  only:
    - master
    - dev

type-check:
  stage:
    - type-check
  script:
    - pnpm run typecheck
  only:
    - master
    - dev

lint-check:
  stage:
    - lint-check
  script:
    - pnpm run lintcheck
  only:
    - master
    - dev
