name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  intallpnpm:
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8


  lintcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


        name: Install pnpm
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8


      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Lint
        run: pnpm run lintcheck

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Typecheck
        run: pnpm run typecheck

  build:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm run build

  build-vercel:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
